name: CI/CD com Validações do Projeto

on:
  push:
    branches: [ main, develop ]
    tags: ['v*', 'v*.*', 'v*.*.*']
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  # =====================
  # Step 1: Vulnerabilities Scan
  # =====================
  vulnerabilities-scan:
    name: Trivy Vulnerabilities Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - name: Scan Dependencies
        run: |
          trivy fs --scanners vuln --vuln-type library --severity CRITICAL,HIGH --exit-code 1 --ignore-unfixed --format table .

  # =====================
  # Step 2: SonarCloud Analysis
  # =====================
  sonarcloud-analysis:
    name: SonarCloud Analysis
    needs: vulnerabilities-scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Build & Test with Jacoco
        run: mvn clean verify
      - name: SonarCloud Scan via Maven
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dockerhub-publish:
    name: Publish Image on DockerHub
    needs: sonarcloud-analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG
        id: vars
        run: |
          if [[ "${{ github.ref_name }}" != "main" && "${{ github.ref_name }}" != "develop" && "${{ github.ref_name }}" != "dependabot/*" ]]; then
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Login in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven (without tests)
        run: mvn clean install -DskipTests

      - name: Build & Pushish to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/lambda-consumer:latest
            ${{ secrets.DOCKERHUB_USER }}/lambda-consumer:${{ steps.vars.outputs.IMAGE_TAG }}